INSERT INTO JOB_TYPE_TBL(id, TYPE_TITLE) VALUES ('1', 'ping');
INSERT INTO JOB_TYPE_TBL(id, TYPE_TITLE) VALUES ('2', 'subdomain');
INSERT INTO JOB_STATUS_TBL(id, STATUS_TITLE) VALUES ('1', 'submitted');
INSERT INTO JOB_STATUS_TBL(id, STATUS_TITLE) VALUES ('2', 'running');
INSERT INTO JOB_STATUS_TBL(id, STATUS_TITLE) VALUES ('3', 'finished');
